import { NextResponse } from "next/server";
import { z } from "zod";
import { nanoid } from "nanoid";
import type { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { requirePlayerAccount } from "@/lib/auth/session";
import { createCheckout, createMomoCharge, type MomoNetworkCode } from "@/lib/payments-service";
import { markFailedDeposit } from "@/lib/deposits/credit";
import { getPlatformSettings } from "@/lib/settings";
import { toMinor, fromMinor } from "@/lib/money";
import { toAccountKind } from "@/lib/accounts/balance";

const bodySchema = z.object({
  amount: z.number().positive(),
  /** Which tab the player chose. For card this preselects the method inside the
   *  Inline modal; for mobile money it now selects the server-side charge path. */
  channel: z.enum(["mobile_money", "card", "any"]).optional(),
  /** Mobile money only — v3 wire values, not the current brand names. */
  network: z.enum(["MTN", "VODAFONE", "TIGO"]).optional(),
  phone: z.string().trim().min(9).max(20).optional(),
  /** Telecel only, generated by the customer dialling *110#. */
  voucher: z.string().trim().min(1).max(20).optional(),
});

/** Human labels for the ledger, matching what withdrawals already write so a
 *  deposit and a withdrawal read the same way in the admin views. */
const NETWORK_LABELS: Record<MomoNetworkCode, string> = {
  MTN: "MTN Mobile Money",
  VODAFONE: "Telecel Cash",
  TIGO: "AirtelTigo Money",
};

/** "direct" (server-side charge) | "inline" (the old browser modal). Defaults
 *  to direct; set DEPOSIT_MOMO_MODE=inline to fall back without a code change
 *  or a schema migration if the server-side path ever misbehaves. */
// `||`, not `??`. With `??`, setting DEPOSIT_MOMO_MODE to an empty string
// yields "" — which matches neither branch, so MoMo silently reverts to the
// old browser modal with nothing in the logs to say why.
const momoMode = () => (process.env.DEPOSIT_MOMO_MODE?.trim() || "direct").toLowerCase();

/**
 * Where to send the player back after paying.
 *
 * Derived from the REQUEST, not from an env var. The player returns to whatever
 * hostname they started on, which is correct by construction when a deployment
 * answers on several — the custom domain and Vercel's own *.vercel.app URL.
 * Reading NEXT_PUBLIC_APP_URL instead sent live players to the deployment URL,
 * because that variable is referenced nowhere else in the app and so had never
 * needed to be right.
 *
 * NEXT_PUBLIC_APP_URL remains a fallback for any context without request
 * headers. The Host header is attacker-controllable in general, but only
 * hostnames configured on the deployment are routed here, and this value
 * decides only where the player LANDS — it moves no money and grants no access.
 */
function returnOrigin(request: Request): string | null {
  const host = request.headers.get("x-forwarded-host") ?? request.headers.get("host");
  if (host) {
    const isLocal = /^(localhost|127\.|\[::1\])/.test(host);
    const proto = request.headers.get("x-forwarded-proto") ?? (isLocal ? "http" : "https");
    return `${proto}://${host}`;
  }
  return process.env.NEXT_PUBLIC_APP_URL?.trim().replace(/\/$/, "") || null;
}

export async function POST(request: Request) {
  const account = await requirePlayerAccount();
  if (!account) return NextResponse.json({ error: "Log in to deposit." }, { status: 401 });

  const json = await request.json().catch(() => null);
  const parsed = bodySchema.safeParse(json);
  if (!parsed.success) return NextResponse.json({ error: "Invalid request." }, { status: 400 });

  const settings = await getPlatformSettings();
  const amountMinor = toMinor(parsed.data.amount);
  if (amountMinor < settings.minDepositAmountMinor) {
    return NextResponse.json(
      { error: `Minimum deposit is GHS ${fromMinor(settings.minDepositAmountMinor).toFixed(2)}.` },
      { status: 400 }
    );
  }

  // One id now, not two. Flutterwave accepts an arbitrary tx_ref, so our own
  // `dep_` reference doubles as the gateway reference — the separate
  // digits-and-dashes id BulkClix required is gone. The `dep_` prefix still
  // matters: downstream accounting keys on it to tell a genuine gateway deposit
  // from a manual credit, and the shared webhook uses it as a routing fallback.
  const reference = `dep_${nanoid(16)}`;

  // Written BEFORE the charge is prepared, so a callback that arrives while
  // we're still awaiting the response has a row to find. The reverse order
  // would lose a fast webhook entirely.
  const channel = parsed.data.channel ?? "any";

  const network = parsed.data.network;
  const useDirectMomo =
    channel === "mobile_money" && momoMode() === "direct" && Boolean(network) && Boolean(parsed.data.phone);
  const momoPhone = parsed.data.phone?.replace(/\D/g, "") || account.phone;

  // Logged on EVERY deposit, not just failures. Which path a deposit took is
  // the first question asked whenever one misbehaves, and reconstructing it
  // afterwards from four separate inputs is exactly the guesswork this avoids.
  console.info(
    `[deposits] ${reference} channel=${channel} momoMode=${momoMode()} ` +
      `network=${network ?? "(none)"} phone=${parsed.data.phone ? "yes" : "(none)"} ` +
      `=> ${useDirectMomo ? "DIRECT server-side charge" : "INLINE browser modal"}`
  );

  // Flutterwave requires an email. Players can sign up with a phone number
  // only, so fall back to a synthetic address — it never receives mail, it just
  // satisfies the gateway.
  const customerEmail =
    account.email?.trim() ||
    `${account.firstName.trim()}${account.lastName.trim()}${Math.floor(Math.random() * 99) + 2}@gmail.com`.toLowerCase();

  await db.transaction.create({
    data: {
      accountId: account.id,
      accountKind: toAccountKind(account.kind),
      type: "DEPOSIT",
      status: "PENDING",
      amountMinor,
      // Under the direct charge we know the instrument exactly, because the
      // player picks it on our own form rather than inside a modal we never see.
      method: channel === "card" ? "Card" : useDirectMomo && network ? NETWORK_LABELS[network] : "Mobile Money",
      // Likewise the number: this is the wallet actually being debited, not
      // merely the phone on the account.
      phone: useDirectMomo ? momoPhone : account.phone,
      network: useDirectMomo && network ? NETWORK_LABELS[network] : undefined,
      reference,
      referringAdminId: account.referrerAdminId ?? undefined,
    },
  });

  const metadata = {
    account_id: account.id,
    account_kind: toAccountKind(account.kind),
  };

  // ── Mobile money: charged server-side ──────────────────────────────────────
  if (useDirectMomo && network) {
    let result;
    try {
      result = await createMomoCharge({
        reference,
        amountMinor,
        network,
        phone: momoPhone!,
        voucher: parsed.data.voucher,
        customer: { email: customerEmail, name: `${account.firstName} ${account.lastName}`.trim() },
        metadata,
        // Absent locally, present behind the proxy. Sent only when real — a
        // placeholder scores worse with fraud checks than a missing value.
        clientIp: request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || undefined,
        // No query string of our own. Flutterwave appends its own `?resp=<json>`
        // on the return leg and does not reliably preserve ours — observed
        // storing a redirect_url of "http://127.0.0", truncated mid-host. The
        // deposit page reads the reference out of `resp.data.txRef` instead.
        // Omitted entirely when unset rather than sent as a relative path, which
        // upstream cannot redirect to.
        redirectUrl: (() => {
          const origin = returnOrigin(request);
          return origin ? `${origin}/account/deposit` : undefined;
        })(),
      });
    } catch (err) {
      // We never reached the gateway, so nothing can arrive for this later.
      await markFailedDeposit(reference, { error: String(err) });
      console.error(`[deposits] MoMo charge unreachable for ${reference}:`, err);
      return NextResponse.json({ error: "Couldn't start the deposit. Please try again." }, { status: 502 });
    }

    // Logged in full regardless of outcome: settlement later overwrites
    // gatewayRaw with the verify envelope, so this is the only durable copy of
    // what the charge itself returned.
    console.info(`[deposits] MoMo charge ${reference} ok=${result.ok} raw=${JSON.stringify(result.gateway)}`);

    if (!result.ok) {
      // PENDING-guarded, never a bare status write — a fast approval can fire
      // charge.completed before this response lands, and stomping SUCCESS to
      // FAILED would reverse a real credit's status while the balance stays put.
      await markFailedDeposit(reference, result.gateway);
      return NextResponse.json(
        { error: result.error ?? "That network declined the payment. Please try again." },
        { status: 502 }
      );
    }

    await db.transaction.update({
      where: { reference },
      data: {
        gatewayRaw: result.gateway as Prisma.InputJsonValue,
        // The gateway's own id. Persisted immediately because some gateways have
        // no lookup by our reference at all — losing this makes the payment
        // permanently unresolvable.
        ...(result.providerRef ? { gatewayTransactionId: String(result.providerRef) } : {}),
      },
    });

    console.info(
      `[deposits] ${reference} -> client action=${result.action} ` +
        `redirectUrl=${result.redirectUrl ? "present" : "NULL"}`
    );

    return NextResponse.json({
      reference,
      mode: "momo_direct",
      action: result.action,
      redirectUrl: result.redirectUrl ?? null,
      instruction: result.instruction ?? null,
    });
  }

  // ── Card (and MoMo with the flag off): the Inline modal ─────────────────────
  // createCheckout is synchronous — it builds the config from env vars with no
  // network call, so there is nothing to catch here.
  const checkout = createCheckout({
    reference,
    amountMinor,
    channel,
    customer: { email: customerEmail, phone: account.phone ?? undefined },
    metadata,
  });

  // The client opens the Flutterwave modal with this; the money is collected
  // in the browser, and the outcome reaches us via the webhook or the status
  // poll below.
  return NextResponse.json({ reference, checkout });
}
